export type RefractionType = "color" | "monochrome"

export type Variant = {
  name: string
  category: string
  baseColor: {
    name: "White" | "Silver" | "Specialty"
    hex: string
  }
  pattern: {
    name: string
    description: string
  }
  refractionType: RefractionType
  refractionRate: number // 0-100
  artClarity: number // 0-100 percentage
  cleanVsBusy: number // 0-100 where 0 is clean, 100 is busy
  complexity: number // 0-1000
  image: string // not implemented anywhere yet
}

export const variants: Variant[] = [
  // Metallics
  {
    name: "Metal",
    category: "metallics",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Brushed Steel", description: "Linear brushed metal texture" },
    refractionType: "monochrome",
    refractionRate: 45,
    artClarity: 85,
    cleanVsBusy: 20,
    complexity: 150,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Chrome",
    category: "metallics",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Mirror Finish", description: "Highly reflective chrome surface" },
    refractionType: "color",
    refractionRate: 95,
    artClarity: 98,
    cleanVsBusy: 10,
    complexity: 80,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Titanium",
    category: "metallics",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Aerospace Grade", description: "Industrial titanium texture" },
    refractionType: "monochrome",
    refractionRate: 55,
    artClarity: 92,
    cleanVsBusy: 25,
    complexity: 200,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Platinum",
    category: "metallics",
    baseColor: { name: "White", hex: "#F5F5F5" },
    pattern: { name: "Precious Metal", description: "Lustrous platinum finish" },
    refractionType: "color",
    refractionRate: 75,
    artClarity: 95,
    cleanVsBusy: 15,
    complexity: 120,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Gold",
    category: "metallics",
    baseColor: { name: "Silver", hex: "#FFD700" },
    pattern: { name: "24K Finish", description: "Pure gold metallic surface" },
    refractionType: "color",
    refractionRate: 85,
    artClarity: 90,
    cleanVsBusy: 20,
    complexity: 180,
    image: "/assets/astro-boy_banner.png",
  },

  // Textures
  {
    name: "Refractor",
    category: "textures",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Light Bending", description: "Prismatic light refraction" },
    refractionType: "color",
    refractionRate: 90,
    artClarity: 88,
    cleanVsBusy: 35,
    complexity: 450,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Holo",
    category: "textures",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Holographic", description: "Rainbow hologram effect" },
    refractionType: "color",
    refractionRate: 95,
    artClarity: 75,
    cleanVsBusy: 60,
    complexity: 650,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Matte",
    category: "textures",
    baseColor: { name: "White", hex: "#F8F8F8" },
    pattern: { name: "Non-Reflective", description: "Smooth matte finish" },
    refractionType: "monochrome",
    refractionRate: 15,
    artClarity: 95,
    cleanVsBusy: 5,
    complexity: 50,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Canvas",
    category: "textures",
    baseColor: { name: "White", hex: "#FFFEF7" },
    pattern: { name: "Fabric Weave", description: "Canvas textile texture" },
    refractionType: "monochrome",
    refractionRate: 25,
    artClarity: 85,
    cleanVsBusy: 30,
    complexity: 280,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Twill",
    category: "textures",
    baseColor: { name: "White", hex: "#FAFAFA" },
    pattern: { name: "Diagonal Weave", description: "Twill fabric pattern" },
    refractionType: "monochrome",
    refractionRate: 20,
    artClarity: 80,
    cleanVsBusy: 40,
    complexity: 320,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Radiant",
    category: "textures",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Light Rays", description: "Radiating light beams" },
    refractionType: "color",
    refractionRate: 80,
    artClarity: 90,
    cleanVsBusy: 50,
    complexity: 520,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Prism",
    category: "textures",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Triangular Facets", description: "Geometric prism surfaces" },
    refractionType: "color",
    refractionRate: 85,
    artClarity: 92,
    cleanVsBusy: 45,
    complexity: 480,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Plaid",
    category: "textures",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Checkered Grid", description: "Classic plaid pattern" },
    refractionType: "monochrome",
    refractionRate: 30,
    artClarity: 75,
    cleanVsBusy: 70,
    complexity: 580,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Griddy",
    category: "textures",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Tech Grid", description: "Digital grid overlay" },
    refractionType: "monochrome",
    refractionRate: 40,
    artClarity: 88,
    cleanVsBusy: 55,
    complexity: 420,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Snakeskin",
    category: "textures",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Scale Pattern", description: "Reptilian scale texture" },
    refractionType: "monochrome",
    refractionRate: 35,
    artClarity: 70,
    cleanVsBusy: 80,
    complexity: 720,
    image: "/assets/astro-boy_banner.png",
  },

  // Effects
  {
    name: "Sequence",
    category: "effects",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Sequin Sparkle", description: "Shimmering sequin effect" },
    refractionType: "color",
    refractionRate: 70,
    artClarity: 65,
    cleanVsBusy: 85,
    complexity: 780,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Starburst",
    category: "effects",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Radial Burst", description: "Explosive star pattern" },
    refractionType: "color",
    refractionRate: 88,
    artClarity: 80,
    cleanVsBusy: 75,
    complexity: 680,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Galactic",
    category: "effects",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Cosmic Swirl", description: "Galaxy spiral pattern" },
    refractionType: "color",
    refractionRate: 92,
    artClarity: 85,
    cleanVsBusy: 65,
    complexity: 750,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Digit",
    category: "effects",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Binary Code", description: "Digital number patterns" },
    refractionType: "monochrome",
    refractionRate: 45,
    artClarity: 90,
    cleanVsBusy: 60,
    complexity: 550,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Disco",
    category: "effects",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Mirror Ball", description: "Disco ball reflections" },
    refractionType: "color",
    refractionRate: 95,
    artClarity: 70,
    cleanVsBusy: 90,
    complexity: 850,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Scale",
    category: "effects",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Dragon Scale", description: "Overlapping scale texture" },
    refractionType: "color",
    refractionRate: 60,
    artClarity: 75,
    cleanVsBusy: 70,
    complexity: 620,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Razz",
    category: "effects",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Dazzle Effect", description: "Chaotic light scatter" },
    refractionType: "color",
    refractionRate: 85,
    artClarity: 60,
    cleanVsBusy: 95,
    complexity: 920,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Angel Dust",
    category: "effects",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Shimmer Dust", description: "Fine glittering particles" },
    refractionType: "color",
    refractionRate: 75,
    artClarity: 85,
    cleanVsBusy: 55,
    complexity: 480,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Bubble",
    category: "effects",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Soap Bubble", description: "Iridescent bubble surface" },
    refractionType: "color",
    refractionRate: 80,
    artClarity: 70,
    cleanVsBusy: 40,
    complexity: 380,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Flash",
    category: "effects",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Lightning Flash", description: "Sudden bright illumination" },
    refractionType: "color",
    refractionRate: 98,
    artClarity: 95,
    cleanVsBusy: 30,
    complexity: 280,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Wave",
    category: "effects",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Fluid Wave", description: "Flowing wave motion" },
    refractionType: "color",
    refractionRate: 65,
    artClarity: 80,
    cleanVsBusy: 45,
    complexity: 420,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Beam",
    category: "effects",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Light Beam", description: "Focused light ray" },
    refractionType: "color",
    refractionRate: 90,
    artClarity: 98,
    cleanVsBusy: 20,
    complexity: 180,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Fractal",
    category: "effects",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Fractal Geometry", description: "Self-repeating patterns" },
    refractionType: "color",
    refractionRate: 85,
    artClarity: 75,
    cleanVsBusy: 85,
    complexity: 950,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Groovy",
    category: "effects",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Wavy Lines", description: "Psychedelic wave pattern" },
    refractionType: "color",
    refractionRate: 70,
    artClarity: 65,
    cleanVsBusy: 80,
    complexity: 720,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Hypnotic",
    category: "effects",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Spiral Vortex", description: "Mesmerizing spiral pattern" },
    refractionType: "color",
    refractionRate: 88,
    artClarity: 70,
    cleanVsBusy: 90,
    complexity: 880,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Wire",
    category: "effects",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Wire Frame", description: "3D wireframe structure" },
    refractionType: "monochrome",
    refractionRate: 40,
    artClarity: 95,
    cleanVsBusy: 60,
    complexity: 520,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Link",
    category: "effects",
    baseColor: { name: "Silver", hex: "#C0C0C0" },
    pattern: { name: "Chain Link", description: "Interconnected chain pattern" },
    refractionType: "monochrome",
    refractionRate: 35,
    artClarity: 85,
    cleanVsBusy: 65,
    complexity: 580,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Atomic",
    category: "effects",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Atomic Structure", description: "Molecular orbital pattern" },
    refractionType: "color",
    refractionRate: 75,
    artClarity: 90,
    cleanVsBusy: 70,
    complexity: 680,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Glass",
    category: "effects",
    baseColor: { name: "White", hex: "#FFFFFF" },
    pattern: { name: "Shattered Glass", description: "Cracked glass surface" },
    refractionType: "color",
    refractionRate: 92,
    artClarity: 88,
    cleanVsBusy: 75,
    complexity: 750,
    image: "/assets/astro-boy_banner.png",
  },

  // Specialties
  {
    name: "Diamond",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Diamond Cut", description: "Brilliant cut facets" },
    refractionType: "color",
    refractionRate: 98,
    artClarity: 100,
    cleanVsBusy: 15,
    complexity: 120,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Alpha",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Prime Pattern", description: "First-generation design" },
    refractionType: "color",
    refractionRate: 95,
    artClarity: 98,
    cleanVsBusy: 10,
    complexity: 80,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Emerald",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Gem Cut", description: "Precious emerald facets" },
    refractionType: "color",
    refractionRate: 90,
    artClarity: 95,
    cleanVsBusy: 20,
    complexity: 150,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Ruby",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Ruby Cut", description: "Deep red gemstone facets" },
    refractionType: "color",
    refractionRate: 88,
    artClarity: 92,
    cleanVsBusy: 25,
    complexity: 180,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Pink Sapphire",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Sapphire Cut", description: "Pink sapphire brilliance" },
    refractionType: "color",
    refractionRate: 92,
    artClarity: 96,
    cleanVsBusy: 18,
    complexity: 140,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Amber",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Fossilized Resin", description: "Ancient amber preservation" },
    refractionType: "color",
    refractionRate: 75,
    artClarity: 85,
    cleanVsBusy: 30,
    complexity: 280,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Amethyst",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Crystal Formation", description: "Purple crystal structure" },
    refractionType: "color",
    refractionRate: 85,
    artClarity: 90,
    cleanVsBusy: 35,
    complexity: 320,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Obsidian",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Volcanic Glass", description: "Sharp obsidian surface" },
    refractionType: "monochrome",
    refractionRate: 95,
    artClarity: 98,
    cleanVsBusy: 5,
    complexity: 60,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Carbon Fiber",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Woven Carbon", description: "High-tech carbon weave" },
    refractionType: "monochrome",
    refractionRate: 60,
    artClarity: 95,
    cleanVsBusy: 40,
    complexity: 450,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Gold Record",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Vinyl Grooves", description: "Record album texture" },
    refractionType: "color",
    refractionRate: 80,
    artClarity: 88,
    cleanVsBusy: 50,
    complexity: 520,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Platinum Record",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Vinyl Grooves", description: "Platinum record texture" },
    refractionType: "color",
    refractionRate: 85,
    artClarity: 92,
    cleanVsBusy: 45,
    complexity: 480,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Transparency",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "See-Through", description: "Transparent overlay effect" },
    refractionType: "color",
    refractionRate: 100,
    artClarity: 100,
    cleanVsBusy: 0,
    complexity: 20,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Papyrus",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#F5F5DC" },
    pattern: { name: "Ancient Paper", description: "Aged papyrus texture" },
    refractionType: "monochrome",
    refractionRate: 10,
    artClarity: 70,
    cleanVsBusy: 60,
    complexity: 580,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Boltfractor",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Lightning Bolt", description: "Electric bolt pattern" },
    refractionType: "color",
    refractionRate: 95,
    artClarity: 90,
    cleanVsBusy: 70,
    complexity: 780,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Gold Boltfractor",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Golden Lightning", description: "Gold electric bolt pattern" },
    refractionType: "color",
    refractionRate: 98,
    artClarity: 95,
    cleanVsBusy: 65,
    complexity: 820,
    image: "/assets/steve-aoki_banner.png",
  },
  {
    name: "Duality",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Split Design", description: "Dual-nature pattern" },
    refractionType: "color",
    refractionRate: 85,
    artClarity: 88,
    cleanVsBusy: 55,
    complexity: 650,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Phantom",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Ghost Effect", description: "Ethereal phantom pattern" },
    refractionType: "monochrome",
    refractionRate: 70,
    artClarity: 75,
    cleanVsBusy: 40,
    complexity: 420,
    image: "/assets/astro-boy_banner.png",
  },
  {
    name: "Crystal",
    category: "specialties",
    baseColor: { name: "Specialty", hex: "#991b1b" },
    pattern: { name: "Crystal Lattice", description: "Perfect crystal structure" },
    refractionType: "color",
    refractionRate: 96,
    artClarity: 98,
    cleanVsBusy: 25,
    complexity: 220,
    image: "/assets/astro-boy_banner.png",
  },
]

export const getCategories = () => {
  const categories = Array.from(new Set(variants.map((v) => v.category)))
  return categories.map((category) => ({
    name: category,
    displayName: category.charAt(0).toUpperCase() + category.slice(1),
    variants: variants.filter((v) => v.category === category),
  }))
}